name: Build
on:
  push:
    branches: [ master, staging ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: SiteGround/configure-aws-credentials@v1.0
        with:
          aws-access-key-id: ${{ secrets.ECR_E2E_IMAGE_UPLOADER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_E2E_IMAGE_UPLOADER_KEY_SECRET }}
          aws-region: eu-central-1
      - name: Login to Docker Repo
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 355580574270.dkr.ecr.eu-central-1.amazonaws.com
      - uses: actions/checkout@v2
      - name: Add CI SSH Key to run npm install during build
        run: echo "${{ secrets.CI_USER_SSH_KEY_PRIVATE }}" > id_ed25519
      - name: Determine Docker Tag
        id: determine_docker_tag
        run: |
          if [ ${{ github.ref }} == refs/heads/master ]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          elif [ ${{ github.ref }} == refs/heads/staging ]; then
            echo "tag=staging" >> "$GITHUB_OUTPUT"
          else 
            BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's|refs/heads/||; s|_||g')
            DOCKER_TAG="$BRANCH_NAME"
            echo "tag=$DOCKER_TAG" >> "$GITHUB_OUTPUT"
          fi
      - name: Print selected docker tag
        run: |
          echo "Docker Tag: ${{ steps.determine_docker_tag.outputs.tag }}"
      - name: Build the image
        run: docker build --target=ci -t 355580574270.dkr.ecr.eu-central-1.amazonaws.com/ecom.playwright-sb:${{ steps.determine_docker_tag.outputs.tag }} .
      - name: Push the image
        run: docker push 355580574270.dkr.ecr.eu-central-1.amazonaws.com/ecom.playwright-sb:${{ steps.determine_docker_tag.outputs.tag }}
